/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend.App;

import backend.Controller.Control;
import backend.Repository.Repo;
import backend.Repository.RepoImpl;
import backend.Services.Serve;
import backend.Services.ServeImpl;
import io.javalin.Javalin;

public class App {
   
        public static void main(String[] args) {
        Javalin app = Javalin.create(
                config ->{
                        config.enableCorsForAllOrigins();
                }
        );
        app.start(); 
        addRoute(app); 
        }

        private static void addRoute(Javalin app){
                Repo r = new RepoImpl();
                Serve s = new ServeImpl(r);
                Control c = new Control(s);
                app.post("/TRMS/register", c.createUser);
                app.post("/TRMS/login", c.login);
                app.get("/TRMS/users/{id}", c.getUser);
                app.post("/TRMS/form", c.createForm);
                app.get("/TRMS/form/{id}", c.getForm);
                app.get("/TRMS/eform/{id}", c.getEForm);
                app.get("/TRMS/formSA", c.getFormSApproval);
                app.get("/TRMS/formHA", c.getFormHApproval);
                app.get("/TRMS/formCA", c.getFormCApproval);
                app.get("/TRMS/formCFA", c.getFormCFApproval);
                app.put("/TRMS/form/{id}", c.updateFormAmount);
                app.put("/TRMS/rform/{id}", c.rejectForm);
                app.put("/TRMS/formSA/{id}", c.updateFormSApproval);
                app.put("/TRMS/formHA/{id}", c.updateFormHApproval);
                app.put("/TRMS/formCA/{id}", c.updateFormCApproval);
                app.put("/TRMS/formCFA/{id}", c.updateFormCFApproval);
                app.post("/TRMS/rform", c.createReimbursments);
                app.post("/TRMS/grade/{id}", c.createGrades);
                app.get("/TRMS/grade/{id}", c.getGrades);
        }
}
